// <auto-generated />
using System.Reflection;
using System.Runtime.InteropServices;

[assembly: AssemblyTitle("Therefore.Game")]
[assembly: AssemblyDescription("")]
[assembly: AssemblyConfiguration("")]
[assembly: AssemblyCompany("John Gietzen")]
[assembly: AssemblyProduct("Therefore")]
[assembly: AssemblyCopyright("Copyright © John Gietzen 2011")]
[assembly: AssemblyTrademark("")]
[assembly: AssemblyCulture("")]

[assembly: ComVisible(false)]

[assembly: Guid("edee72ea-6930-41e3-bf26-933ad90e2f15")]

[assembly: AssemblyVersion("1.0.0.0")]
[assembly: AssemblyFileVersion("1.0.0.0")]
